# This is a basic workflow to help you get started with Actions

name: create-failure-issue

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab

  workflow_dispatch:
    inputs:
      title:
        description: 'Issue title'
        required: true
      body:
        description: 'Issue body'
        required: true
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  create_issue_on_failure:

  runs-on: ubuntu-latest
  needs: test-run
  if: always() && failure()
  steps:
    - name: invoke workflow to create issue
      run: >
        curl -X POST
        -H "authorization: Bearer ${{ secrets.PIPELINE_USE }}"
        -H "Accept: application/vnd.github.v3+json"
        "https://api.github.com/repos/${{ github.repository }}/actions/workflows/create-failure-issue.yml/dispatches"
        -d '{"ref":"main",
            "inputs":
            {"title":"Automated workflow failure issue for commit ${{ github.sha }}",
            "body":"This issue was automatically created by the GitHub Action workflow ** ${{ github.workflow }} **"}
            }'
      
